### ISSUE TITLE
G.1 Главная страница: G.1.1 Просмотр главной страницы

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#1]
Написать проверки

- [ ] Проверки для хедера @danilastepanov 
- [ ] Проверки для футера @danilastepanov 
- [ ] Проверки для бади @danilastepanov 
- [ ] Проверка формы обратной связи функционал @danilastepanov 
- [ ] Проверки для формы обратной связи валидация @danilastepanov  (к 26.10)

**Comment by danilastepanov** [comment]
- [ ]  Проверки для хедера @danilastepanov
- [ ]  Проверки для футера @danilastepanov
- [ ]  Проверки для бади @danilastepanov
- [ ]  Проверка формы обратной связи функционал @danilastepanov
