### ISSUE TITLE
R.5 Регистрация:R.5.2 Регистрация организатора

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#10]
Протестировать 

- [x] Поля формы регистрации организатора (валидация) @KashinaOksi 
- [x] АПИ регистрации организатора @danilastepanov 
- [x] Функциональность 1920 @danilastepanov 
- [x] Функциональность 1366 @danilastepanov

**Comment by danilastepanov** [comment]
- [ ] Апи

**Comment by danilastepanov** [comment]
Протестировать в 1920
Функциональность

Протестировать в 1366

 Поля формы регистрации волонтера (валидация)
 Функционал
 Сверка с макетами в Figma (без проверок для верстки)

**Comment by KashinaOksi** [comment]
- [ ] Поля формы регистрации организатора (валидации)
![Тест-ран регистрация волонтера валидация](https://github.com/volunteers-for-city-projects/QA/assets/146958241/1f0b0b9a-fcff-4707-b057-8aaa5388cbf3)
