### ISSUE TITLE
LV.3 Личный кабинет волонтера: LV.3.1 Просмотр анкеты волонтера

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#13]
- [x] Написать проверки для просмотра анкеты волонтера (функционал) @KashinaOksi 
- [x] API просмотра анкеты волонтера @Twilight-Messiah 

Проверить что в ЛК отображаются те же данные из БД, что были добавлены при регистрации

**Comment by kseniia2673** [comment]
тут еще забыла написать проверки для АПИ просмотра анкеты волонтера

**Comment by KashinaOksi** [comment]
- [ ] Написать проверки для просмотра анкеты волонтера (функционал) https://app.qase.io/project/VOLUNTEERS?previewMode=side&suite=390

**Comment by Twilight-Messiah** [comment]
просмотр анкеты волонтера [есть](https://app.qase.io/project/VOLUNTEERS?suite=452)
