### ISSUE TITLE
LV.3 Личный кабинет волонтера: LV.3.1 Просмотр анкеты волонтера

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#14]
Протестировать 1920
- [x] Протестировать просмотр анкеты волонтера (функционал) @KashinaOksi (пока не тестируем тк будет переделано на фронте)
- [x] Апи @Twilight-Messiah 

Протестировать 1366
- [x] Протестировать просмотр анкеты волонтера (функционал) @KashinaOksi

**Comment by Twilight-Messiah** [comment]
АПИ просмотра [протестирован](https://app.qase.io/run/VOLUNTEERS/dashboard/40)

**Comment by KashinaOksi** [comment]
- [ ]  Протестировать просмотр анкеты волонтера (функционал) 1920 [Тест-ран 73](https://app.qase.io/run/VOLUNTEERS/dashboard/73)
- [ ]  Протестировать просмотр анкеты волонтера (функционал) 1366
