### ISSUE TITLE
LV.3 Личный кабинет волонтера: LV.3.2 Редактирование анкеты волонтера

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#15]
LV.3.2.1 Редактирование анкеты волонтера
- [x] Написать проверки для редактирования анкеты волонтера (функционал) @Twilight-Messiah 
- [x] Апи редактирования анкеты волонтера @Twilight-Messiah 
- [x] Редактирование анкеты волонтера (валидация) @Twilight-Messiah 

LV.3.2.2 Редактирование анкеты волонтера (изменение пароля)

- [x] АПИ изменения пароля @danilastepanov 
- [x] Валидация изменения пароля
- [x] Функционал изменения пароля

**Comment by Twilight-Messiah** [comment]
редактирование валидации сделано

**Comment by Twilight-Messiah** [comment]
АПИ регистрации [сделан](https://app.qase.io/project/VOLUNTEERS?previewMode=side&suite=455)

**Comment by Twilight-Messiah** [comment]
здесь будет валидация смены пароля

**Comment by Twilight-Messiah** [comment]
здесь будет функционал смены пароля

**Comment by Twilight-Messiah** [comment]
здесь будет функционал просмотра
