### ISSUE TITLE
LV.3 Личный кабинет волонтера: LV.3.2 Редактирование анкеты волонтера

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#16]
LV.3.2.1 Редактирование анкеты волонтера

- [x] редактирования анкеты волонтера (функционал) 1920 (пока не работает)
- [x] Апи редактирования анкеты волонтера  
- [x] Редактирование анкеты волонтера (валидация) 
- [ ] редактирования анкеты волонтера (функционал) 1366

LV.3.2.2 Редактирование анкеты волонтера (изменение пароля)

- [x] АПИ изменения пароля @danilastepanov 
- [x] Валидация изменения пароля
- [x] Функционал изменения пароля

**Comment by danilastepanov** [comment]
- [ ] АПИ изменения пароля [АПИ /auth/change_password/ 2023/11/07](https://app.qase.io/public/report/0ba6479afcf8696536ae41e97b1b542d6fc99fd7)

**Comment by Twilight-Messiah** [comment]
API редактирования пароля [здесь](https://app.qase.io/run/VOLUNTEERS/dashboard/53)

**Comment by Twilight-Messiah** [comment]
Валидация смены пароля [здесь](https://app.qase.io/run/VOLUNTEERS/dashboard/54)

**Comment by Twilight-Messiah** [comment]
здесь будет функционал редактирования

**Comment by Twilight-Messiah** [comment]
здесь будет функционал смены пароля
