### ISSUE TITLE
LO.4 Личный кабинет организатора	LO.4.2 Редактирование анкеты организатора

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#18]
LO.4.2.1 Редактирование анкеты организатора

- [x] Написать проверки для редактирования анкеты организатора (функционал) @mimimila 
- [x] Апи редактирования анкеты организатора @danilastepanov 
- [x] Редактирование анкеты организатора (валидация) @mimimila 

 LO.4.2.2 Редактирование профиля организатора (изменение пароля)

- [x] АПИ изменения пароля @danilastepanov 
- [x] Валидация изменения пароля @mimimila 
- [x] Функционал изменения пароля @mimimila

**Comment by mimimila** [comment]
- [x] - Редактирование анкеты организатора (валидация)  [Suite 139](https://app.qase.io/project/VOLUNTEERS?previewMode=side&suite=139)
- [x] - Редактирование анкеты организатора (функционал) [Suite 243](https://app.qase.io/project/VOLUNTEERS?previewMode=side&suite=243)
- [ ] - Апи редактирования анкеты организатора

**Comment by danilastepanov** [comment]
- [ ]  Апи редактирования анкеты организатора @danilastepanov
