### ISSUE TITLE
LO.4 Личный кабинет организатора	LO.4.1 Просмотр анкеты организатора

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#19]
- [x] Написать проверки для просмотра анкеты организатора (функционал)
- [x] Апи просмотра анкеты организатора

Проверить что в ЛК отображаются те же данные из БД, что были добавлены при регистрации

**Comment by KashinaOksi** [comment]
- [ ] Написать проверки для просмотра анкет организатора (функционал)

- [ ] Апи посмотреть анкеты организатора
