### ISSUE TITLE
G.1 Главная страница: G.1.1 Просмотр главной страницы

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#2]
Протестировать в 1920
- [ ] Проверки для хедера 
- [ ] Проверки для футера 
- [ ] Проверки для бади 
- [ ] Проверка формы обратной связи функционал 
- [ ] Проверки для формы обратной связи валидация 
- [ ] Сверка с макетами в Figma (без проверок для верстки)

Протестировать в 1366
- [ ] Проверки для хедера 
- [ ] Проверки для футера 
- [ ] Проверки для бади 
- [ ] Проверка формы обратной связи функционал 
- [ ] Проверки для формы обратной связи валидация 
- [ ] Сверка с макетами в Figma (без проверок для верстки)

**Comment by danilastepanov** [comment]
[Тест ран: Просмотр главной страницы 2023/11/04](https://app.qase.io/public/report/0b8d539db56c4511fc8129a03ccff8c219bf6c8c)
- [ ]  Проверки для хедера
- [ ]  Проверки для футера
- [ ]  Проверки для бади
- [ ]  Проверка формы обратной связи функционал
- [ ]  Проверки для формы обратной связи валидация
- [ ]  Сверка с макетами в Figma (без проверок для верстки)
- [ ] Протестировать в 1366
- [ ] 
- [ ]  Проверки для хедера
- [ ]  Проверки для футера
- [ ]  Проверки для бади
- [ ]  Проверка формы обратной связи функционал
- [ ]  Проверки для формы обратной связи валидация
- [ ]  Сверка с макетами в Figma (без проверок для верстки)
