### ISSUE TITLE
LO.4 Личный кабинет организатора	LO.4.3 Добавление нового проекта

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#20]
- [x] Апи добавления нового проекта
- [x] Валидация полей
- [x] Функционал

**Comment by danilastepanov** [comment]
- [ ]  Апи добавления нового проекта

**Comment by mimimila** [comment]
- [ ] Валидация полей [Suit 256](https://app.qase.io/project/VOLUNTEERS?suite=256)
- [ ] Функционал [Suit 299](https://app.qase.io/project/VOLUNTEERS?suite=299)
