### ISSUE TITLE
LO.4 Личный кабинет организатора	LO.4.4 Просмотр превью проектов организатора

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#21]
- [x] Апи просмотра проектов организатора
- [x] функционал (корректно ли отображается)

**Comment by mimimila** [comment]
- [ ] Апи просмотров проекта организатора [Suit 364](https://app.qase.io/project/VOLUNTEERS?previewMode=side&suite=364)

**Comment by kseniia2673** [comment]
#21

**Comment by mimimila** [comment]
- [ ] [Просмотр превью проектов организатора Функционал 1920, 1366](https://app.qase.io/run/VOLUNTEERS/dashboard/105)
- [ ]
