### ISSUE TITLE
LO.4 Личный кабинет организатора	LO.4.3 Добавление нового проекта

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#23]
Протестировать 1920

- [x] Апи добавления нового проекта @danilastepanov
- [x] Валидация полей @mimimila 
- [x] Функционал @mimimila 

Протестировать 1366

- [x] Функционал @mimimila

**Comment by danilastepanov** [comment]
- [ ] Апи добавления нового проекта @danilastepanov

**Comment by mimimila** [comment]
- [ ] Функционал 1366 [Добавление нового проекта организатора Функционал 1366](https://app.qase.io/run/VOLUNTEERS/dashboard/99)
- [ ] Функционал 1920 [Добавление нового проекта организатора Функционал 1920](https://app.qase.io/run/VOLUNTEERS/dashboard/93)
- [ ] Валидация [Добавление нового проекта организатора (Валидация)](https://app.qase.io/run/VOLUNTEERS/dashboard/60)
