### ISSUE TITLE
LO.4 Личный кабинет организатора	LO.4.1 Просмотр анкеты организатора

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#25]
Протестировать 1920

- [x] просмотр анкеты организатора (функционал)
- [x] Апи просмотра анкеты организатора

Протестировать 1366

- [x] просмотр анкеты организатора (функционал)

**Comment by KashinaOksi** [comment]
- [ ] Апи посмотреть анкеты организатора
![2023-11-08_01-41-30](https://github.com/volunteers-for-city-projects/QA/assets/146958241/73e8abb7-863b-482e-900b-1bc778d3c243)

**Comment by KashinaOksi** [comment]
- [ ] Протестировать 1920

 просмотр анкеты организатора (функционал) 

![Image](https://github.com/volunteers-for-city-projects/QA/assets/146958241/1998ccc3-9e53-435a-81b9-4f9b5962799e)

**Comment by KashinaOksi** [comment]
- [ ] Протестировать 1366

 просмотр анкеты организатора (функционал)


![Image](https://github.com/volunteers-for-city-projects/QA/assets/146958241/983f6eea-d951-4765-97c6-ebd075c29d7b)
