### ISSUE TITLE
V2. Авторизация и восстановление пароля: V2.3 Создание кнопки "Вход" отправляющей данные пользователя на сервер для авторизации

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#26]
Протестировать функционал кнопки 

- [x] Протестировать функционал кнопки 1920
- [x] Протестировать функционал кнопки 1366

**Comment by Meshvez01** [comment]
Протестировать функционал кнопки

- [ ]  Протестировать функционал кнопки 1920
- [ ]  Протестировать функционал кнопки 1366
