### ISSUE TITLE
V2. Авторизация и восстановление пароля: V2.1 Создание формы входа и функционала авторизации зарегистрированного пользователя

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#3]
Написать проверки

- [ ] Проверки для авторизации волонтера/организатора (валидация) @Meshvez01 
- [ ] Апи к авторизации @Meshvez01 
- [ ] Проверки для авторизации (функционал) @Meshvez01

**Comment by Meshvez01** [comment]
- [ ] Проверки для авторизации волонтера/организатора (валидация)

- [ ] Апи к авторизации

- [ ] Проверки для авторизации
