### ISSUE TITLE
P.7 Проекты	P.7.3 Просмотр карточки проекта + LO.4 Личный кабинет организатора	LO.4.6 Просмотр карточки проекта организатора

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#37]
Написать проверки

Просмотр карточки проектов:

- [x] АПИ

Просмотр карточки активных проектов

- [x] Функционал 

Просмотр карточки завершенных проектов

- [x] Функционал

**Comment by mimimila** [comment]
- [ ] Апи [364](https://app.qase.io/project/VOLUNTEERS?previewMode=side&suite=364)
