### ISSUE TITLE
V2. Авторизация и восстановление пароля: V2.2 Создание формы восстановления пароля и функционала смены пароля по ссылке

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#4]
Написать проверки для 

- [ ] Восстановление пароля (валидация) @Meshvez01 
- [ ] Восстановление пароля АПИ @Meshvez01 
- [ ] Восстановление пароля (функционал) @Meshvez01

**Comment by Meshvez01** [comment]
- [ ] Восстановление аккаунта (проверка)
- [ ] Восстановление пароля АПИ
- [ ] Восстановление президента (функционал)
