### ISSUE TITLE
P.7 Проекты	P.7.4 Подать заявку на участие

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#44]
Написать проверки: 

- [x] Функционал 
- [x] Апи  
- [x] Валидация

**Comment by KashinaOksi** [comment]
- [ ] Функционал 
Авторизованный [Suite 516](https://app.qase.io/project/VOLUNTEERS?previewMode=side&suite=516), 
неавторизованный [Suite 526](https://app.qase.io/project/VOLUNTEERS?previewMode=side&suite=526)
- [ ] Валидация [Suite 517](https://app.qase.io/project/VOLUNTEERS?previewMode=side&suite=517)
- [ ] Апи
