### ISSUE TITLE
P.7 Проекты	P.7.4 Подать заявку на участие

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#45]
Протестировать: 

- [ ] Функционал 
- [x] Апи   
- [x] Валидация

**Comment by KashinaOksi** [comment]
- [ ]  Функционал 
 

- [ ] Апи  [Test runs 92 ](https://app.qase.io/run/VOLUNTEERS/dashboard/92)

 

- [ ] Валидация
