### ISSUE TITLE
LO.4 Личный кабинет организатора LO.4.8 Удаление карточки проекта

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#47]
Написать проверки: 

- [x] Функционал 
- [x] Апи

**Comment by Twilight-Messiah** [comment]
API [готов](https://app.qase.io/project/VOLUNTEERS?suite=591)

**Comment by Twilight-Messiah** [comment]
Функционал и верстка [готовы](https://app.qase.io/project/VOLUNTEERS?previewMode=side&suite=614)
