### ISSUE TITLE
V2. Авторизация и восстановление пароля: V2.1 Создание формы входа и функционала авторизации зарегистрированного пользователя

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#5]
Протестировать в 1920

- [x] Валидация при авторизации волонтера/организатора 
- [x] Апи к авторизации @danilastepanov 
- [x] Функционал 

Протестировать в 1366

- [x] Функционал

**Comment by Meshvez01** [comment]
Протестировать в 1920
- [ ]  Валидация при авторизации волонтера/организатора
- [ ] Апи к авторизации
- [ ] Функционал
 Функционал
- [ ]  Функционал

**Comment by danilastepanov** [comment]
- [ ]  Апи к авторизации @danilastepanov
