### ISSUE TITLE
V2. Авторизация и восстановление пароля: V2.2 Создание формы восстановления пароля и функционала смены пароля по ссылке

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#6]
Протестировать в 1920

- [x] Восстановление пароля (валидация) 
- [x] Восстановление пароля АПИ @danilastepanov 
- [x] Восстановление пароля (функционал) @danilastepanov 

Протестировать в 1366

- [x] Восстановление пароля (функционал) @danilastepanov

**Comment by Meshvez01** [comment]
Протестировать в 1920

- [ ]  Восстановление пароля (валидация)
- [ ]  Восстановление пароля АПИ
- [ ] Восстановление пароля (функционал)

Протестировать в 1366

- [ ] Восстановление пароля (функционал)

**Comment by danilastepanov** [comment]
Восстановление пароля АПИ @danilastepanov
 Восстановление пароля (функциональность) @danilastepanov
Протестировать в 1366
 Восстановление пароля (функциональность) @danilastepanov
