### ISSUE TITLE
R.5 Регистрация: R.5.1 Регистрация волонтера

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#7]
Написать проверки:

- [x] Проверки полей регистрации волонтера (валидация) @Twilight-Messiah 
- [x] Апи к регистрации волонтера @Twilight-Messiah
- [x] Проверка функциональности @danilastepanov

**Comment by danilastepanov** [comment]
- [ ] Проверка функциональности

**Comment by Twilight-Messiah** [comment]
валидация регистрации сделана
