### ISSUE TITLE
R.5 Регистрация:R.5.2 Регистрация организатора

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/QA#8]
Написать проверки: 

- [ ] Проверки полей регистрации организатора (валидация полей) @KashinaOksi 
- [ ] Проверки полей регистрации организатора (функциональность) @danilastepanov 
- [ ] Апи организатора @danilastepanov

**Comment by danilastepanov** [comment]
- [ ] Проверки полей регистрации организатора (функциональность)
- [ ] Апи организатора
